#:include kv/homescreen.kv
#:include kv/settingsscreen.kv
#:include kv/tabscreen.kv

GridLayout:
    cols: 1
    ScreenManager:
        id: screen_manager
        TabScreen:
            name: "Tab_Screen"
            id: tab_screen
        HomeScreen:
            name: "Home_Screen"
            id: home_screen
        SettingsScreen:
            name: "Settings_Screen"
            id: settings_screen
